### ISSUE TITLE
obj.propertyIsEnumerable is not a function

### ISSUE THREAD

**Issue by zensh** [sindresorhus/object-assign#15]
io.js v2.2.1
```
standard: Unexpected linter output:

TypeError: obj.propertyIsEnumerable is not a function
    at /Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/node_modules/object-assign/index.js:19:14
    at Array.filter (native)
    at ownEnumerableKeys (/Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/node_modules/object-assign/index.js:18:14)
    at module.exports (/Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/node_modules/object-assign/index.js:30:10)
    at addDeclaredGlobals (/Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/lib/eslint.js:139:5)
    at EventEmitter.module.exports.api.verify (/Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/lib/eslint.js:702:13)
    at processFile (/Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/lib/cli-engine.js:197:27)
    at /Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/lib/cli-engine.js:332:26
    at walk (/Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/lib/util/traverse.js:81:9)
    at /Users/zensh/git/js/toa/node_modules/standard/node_modules/eslint/lib/util/traverse.js:102:9

If you think this is a bug in `standard`, open an issue: https://github.com/feross/standard
```

**Comment by ruslansagitov** [comment]
:+1:

**Comment by zensh** [comment]
```
console.log(obj, obj.propertyIsEnumerable):
{ Array: false,
  ArrayBuffer: false,
  Boolean: false,
  constructor: false,
  Date: false,
  decodeURI: false,
  decodeURIComponent: false,
  encodeURI: false,
  encodeURIComponent: false,
  Error: false,
  eval: false,
  EvalError: false,
  Float32Array: false,
  Float64Array: false,
  Function: false,
  hasOwnProperty: false,
  Infinity: false,
  Int16Array: false,
  Int32Array: false,
  Int8Array: false,
  isFinite: false,
  isNaN: false,
  isPrototypeOf: false,
  JSON: false,
  Map: false,
  Math: false,
  NaN: false,
  Number: false,
  Object: false,
  parseFloat: false,
  parseInt: false,
  Promise: false,
  propertyIsEnumerable: false,
  Proxy: false,
  RangeError: false,
  ReferenceError: false,
  Reflect: false,
  RegExp: false,
  Set: false,
  String: false,
  Symbol: false,
  SyntaxError: false,
  System: false,
  toLocaleString: false,
  toString: false,
  TypeError: false,
  Uint16Array: false,
  Uint32Array: false,
  Uint8Array: false,
  Uint8ClampedArray: false,
  undefined: false,
  URIError: false,
  valueOf: false,
  WeakMap: false,
  WeakSet: false } false
```

**Comment by qubyte** [comment]
This is breaking ESLint right now too.

**Comment by markgoodyear** [comment]
I'm getting similar with ESLint: `TypeError: boolean is not a function`.

**Comment by jhorwit2** [comment]
```
/Users/horwitz/programming/github/fluxthis/node_modules/gulp-eslint/node_modules/object-assign/index.js:19
                return obj.propertyIsEnumerable(key);
                           ^
TypeError: boolean is not a function
```

**Comment by sindresorhus** [comment]
Sorry about that. I've pulled the version. Not sure why it would be a problem though.

**Comment by qubyte** [comment]
Could the object be being created by `Object.create(null)`?

**Comment by zensh** [comment]
@qubyte Yes!

**Comment by qubyte** [comment]
It might be safer to do `Object.prototype.propertyIsEnumerable.call(obj, key);`

**Comment by sindresorhus** [comment]
@qubyte Yeah, just hit me too.

**Comment by qubyte** [comment]
That's a cool bug. :D

**Comment by sindresorhus** [comment]
Fix here: https://github.com/sindresorhus/object-assign/pull/16

**Comment by sindresorhus** [comment]
Fixed now. Did a major release for Symbol support in case there are other issues.

**Comment by qubyte** [comment]
Amazing turnaround time. Thanks. :+1:

**Comment by lukewaite** [comment]
Thanks!

**Comment by msolli** [comment]
Would you mind publishing a 2.1.1 with the same fix, but without whatever breaking changes that made it into 3.0.0?

The published 2.1.0 was pulled down to our local registry. I imagine others might have the same problem. Now eslint fails because it depends on ^2.0.0, and it will still get 2.1.0 even though you pulled it. This goes to show once something is on the interwebs it stays there. :)

**Comment by tomgco** [comment]
> Would you mind publishing a 2.1.1 with the same fix, but without whatever breaking changes that made it into 3.0.0?
> 
> The published 2.1.0 was pulled down to our local registry. I imagine others might have the same problem. Now eslint fails because it depends on ^2.0.0, and it will still get 2.1.0 even though you pulled it. This goes to show once something is on the interwebs it stays there. :)

Yup, had this issue as well, see https://github.com/eslint/eslint/pull/2690#issuecomment-109302560

**Comment by sindresorhus** [comment]
Done.

> This goes to show once something is on the interwebs it stays there.

I would rather say it goes to show a lot of users have broken local registries that needs fixing.
